version: '3.8'

services:
  sql:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - compose_1_shared_network

  nosql:
    image: mongo:4.4
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - compose_1_shared_network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - compose_1_shared_network

  db_insert:
    build:
      context: .
      dockerfile: Dockerfile-1
    container_name: db_insert_container
    depends_on:
      - sql
      - nosql
      - redis
    networks:
      - compose_1_shared_network
    volumes:
      - .:/app

  wp_update:
    build:
      context: .
      dockerfile: Dockerfile-2
    container_name: wp_update_container
    networks:
      - compose_1_shared_network
    volumes:
      - .:/app

networks:
  compose_1_shared_network:
    external: true

volumes:
  postgres_data:
  mongo_data:
  redis_data:

